import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { validateEmail, validationError } from '@/lib/validate'
import { logAudit } from '@/lib/audit'

export async function POST(request: NextRequest) {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Caller must be enterprise_admin
  const { data: callerProfile, error: profileError } = await supabase
    .from('profiles')
    .select('role, organization_id')
    .eq('id', user.id)
    .single()

  if (profileError || !callerProfile) {
    return NextResponse.json({ error: 'Profile not found' }, { status: 403 })
  }

  if (callerProfile.role !== 'enterprise_admin') {
    return NextResponse.json({ error: 'Only admins can send invitations' }, { status: 403 })
  }

  if (!callerProfile.organization_id) {
    return NextResponse.json({ error: 'No organisation associated' }, { status: 403 })
  }

  const body = await request.json()
  const { email, role } = body

  // Validate
  const errors: Record<string, string> = {}

  if (!email || !validateEmail(String(email))) {
    errors.email = 'Invalid email address'
  }

  const validRoles = ['enterprise_admin', 'analyst', 'viewer']
  if (!role || !validRoles.includes(role)) {
    errors.role = `Invalid role. Must be one of: ${validRoles.join(', ')}`
  }

  if (Object.keys(errors).length > 0) {
    return NextResponse.json(validationError(errors), { status: 422 })
  }

  const orgId = callerProfile.organization_id

  // Check for existing pending invitation
  const { data: existing } = await supabase
    .from('invitations')
    .select('id, status')
    .eq('org_id', orgId)
    .eq('email', email.toLowerCase())
    .eq('status', 'pending')
    .maybeSingle()

  if (existing) {
    return NextResponse.json({ error: 'A pending invitation already exists for this email' }, { status: 409 })
  }

  // Insert invitation — token generated by DB default
  const { data: invitation, error: insertError } = await supabase
    .from('invitations')
    .insert({
      org_id: orgId,
      email: email.toLowerCase(),
      role,
      invited_by: user.id,
    })
    .select()
    .single()

  if (insertError) {
    console.error('[team/invite] insert error:', insertError)
    return NextResponse.json({ error: 'Failed to create invitation', detail: insertError.message }, { status: 500 })
  }

  logAudit({
    orgId,
    userId: user.id,
    action: 'user.invited',
    resourceType: 'invitation',
    resourceId: invitation.id,
    metadata: { invited_email: email.toLowerCase(), role },
    request,
  })

  return NextResponse.json({ invitation }, { status: 201 })
}

// DELETE — revoke a pending invitation
export async function DELETE(request: NextRequest) {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: callerProfile } = await supabase
    .from('profiles')
    .select('role, organization_id')
    .eq('id', user.id)
    .single()

  if (!callerProfile || callerProfile.role !== 'enterprise_admin') {
    return NextResponse.json({ error: 'Only admins can revoke invitations' }, { status: 403 })
  }

  const { searchParams } = new URL(request.url)
  const id = searchParams.get('id')

  if (!id) {
    return NextResponse.json({ error: 'Invitation ID required' }, { status: 400 })
  }

  // Verify invitation belongs to caller's org
  const { data: invitation } = await supabase
    .from('invitations')
    .select('id, org_id')
    .eq('id', id)
    .maybeSingle()

  if (!invitation || invitation.org_id !== callerProfile.organization_id) {
    return NextResponse.json({ error: 'Invitation not found' }, { status: 404 })
  }

  const { error: updateError } = await supabase
    .from('invitations')
    .update({ status: 'expired' })
    .eq('id', id)

  if (updateError) {
    return NextResponse.json({ error: 'Failed to revoke invitation' }, { status: 500 })
  }

  return NextResponse.json({ success: true })
}
